apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    # Port for the Reader App
    - name: reader
      port: 80
      protocol: TCP
      targetPort: 9090
    # Port for the Writer App
    - name: writer
      port: 9091
      protocol: TCP
      targetPort: 9091