apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: log-output-app-svc
spec:
  type: LoadBalancer
  selector:
    app: log-output-app # This is the app as declared in the deployment.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090