apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: apps-configmap
      containers:
        - name: log-output-app
          image: europe-north1-docker.pkg.dev/dwk-gke-485610/my-repo/log-output-app:2.7
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: apps-configmap
                key: MESSAGE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: apps-configmap
                key: PORT