apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-app
  template:
    metadata:
      labels:
        app: todo-backend-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres-svc 5432; do
                echo "waiting for postgres..."
                sleep 2
              done
      containers:
        - name: todo-backend-app
          image: todo-backend-app:2.10
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: BACKEND_PORT