apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090