apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-configmap
data:
  FRONTEND_PORT: '8080'
  BACKEND_PORT: '9090'
  BACKEND_URL: http://todo-backend-svc:80
  DATABASE_URL: "postgres://john:abc123@postgres-svc:5432/todos?sslmode=disable"