apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-frontend-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080