apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend-app
  template:
    metadata:
      labels:
        app: todo-frontend-app
    spec:
      volumes:
        - name: shared-images
          persistentVolumeClaim:
            claimName: images-claim
      containers:
        - name: todo-frontend-app
          image: todo-frontend-app:2.2
          volumeMounts:
          - name: shared-images
            mountPath: /cache