apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: frontend-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend-app
  template:
    metadata:
      labels:
        app: todo-frontend-app
    spec:
      volumes:
        - name: shared-images
          persistentVolumeClaim:
            claimName: images-claim
      containers:
        - name: todo-frontend-app
          image: europe-north1-docker.pkg.dev/dwk-gke-485610/my-repo/todo-frontend-app:2.10
          imagePullPolicy: Always
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: todo-configmap
                key: FRONTEND_PORT
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: todo-configmap
                key: BACKEND_URL
          volumeMounts:
          - name: shared-images
            mountPath: /cache