apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: todos-routes
  namespace: project
spec:
  parentRefs:
  - name: todos-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: todo-frontend-svc
      port: 80

  - matches:
    - path:
        type: PathPrefix
        value: /todos
    backendRefs:
    - name: todo-backend-svc
      port: 80
